name: blowe_bloc
description: "An advanced Flutter package for state management and business logic components, extending flutter_bloc."
version: 0.2.6
repository: https://github.com/santiagogonzalezblowe/blowe_bloc
issue_tracker: https://github.com/santiagogonzalezblowe/blowe_bloc/issues
homepage: https://www.linkedin.com/in/santiagogonzalezblowe/
topics: [bloc, state-management, pagination, widgets, form]

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
