name: blowe_bloc
description: "An advanced Flutter package for state management and business logic components, extending flutter_bloc."
version: 0.4.7
repository: https://github.com/santiagogonzalezblowe/blowe_bloc
issue_tracker: https://github.com/santiagogonzalezblowe/blowe_bloc/issues
homepage: https://www.linkedin.com/in/santiagogonzalezblowe/
topics: [bloc, state-management, pagination, widgets, form]

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
